# Generated by Django 3.0.11 on 2021-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('work_area', models.CharField(max_length=25, verbose_name='area laboral')),
                ('position', models.CharField(max_length=25, verbose_name='cargo que desempeñan')),
                ('technical_support_request', models.PositiveIntegerField(default=0)),
                ('loans_request', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Solo un usuario activo puede interactuar con el sistema', verbose_name='estado de rol activo')),
            ],
            options={
                'db_table': 'tbl_empleados',
            },
        ),
    ]
