# Generated by Django 3.0.11 on 2021-02-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLoans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('implements_available', models.PositiveIntegerField(default=0)),
                ('implements_used', models.PositiveIntegerField(default=0)),
                ('total_implements', models.PositiveIntegerField(default=0)),
                ('last_admission', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_inventario_prestamos',
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('auxiliary_id', models.IntegerField(null=True)),
                ('loans_location', models.CharField(max_length=50)),
                ('event_google_id', models.CharField(max_length=100, null=True)),
                ('loans_date', models.DateTimeField()),
                ('complete_loans_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se utiliza para marcar cuando el soporte fue completado o cancelado', verbose_name='estado de activo')),
                ('comments', models.TextField(blank=True, null=True)),
                ('ammount_implements', models.PositiveIntegerField()),
                ('ticket', models.FileField(blank=True, upload_to='tickets/reports/')),
                ('assigned_auxiliary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.Assistant')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.InventoryLoans')),
            ],
            options={
                'db_table': 'tbl_prestamos',
            },
        ),
    ]
