# Generated by Django 3.0.11 on 2021-02-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_calificacion_soporte',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('auxiliary_id', models.IntegerField(null=True)),
                ('support_location', models.CharField(max_length=50)),
                ('event_google_id', models.CharField(max_length=100, null=True)),
                ('support_date', models.DateTimeField()),
                ('complete_support_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se utiliza para marcar cuando el soporte fue completado o cancelado', verbose_name='estado de activo')),
                ('description_problem', models.TextField()),
                ('assigned_auxiliary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.Assistant')),
            ],
            options={
                'db_table': 'tbl_soporte',
            },
        ),
    ]
