# Generated by Django 3.0.11 on 2021-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical_support', '0002_auto_20210218_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status_support',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
