# Generated by Django 3.0.11 on 2021-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_request_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status_maintenance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
