# Generated by Django 3.0.11 on 2021-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('availability', models.BooleanField(default=True, help_text='Disponibilidad del auxiliar de sistemas')),
                ('reputation', models.FloatField(default=5.0, help_text='Reputación del auxiliar basada en la calificación de los servicios completados')),
                ('is_active', models.BooleanField(default=True, help_text='Solo un usuario activo puede interactuar con el sistema', verbose_name='estado de rol activo')),
                ('technical_support_completed', models.PositiveIntegerField(default=0)),
                ('loans_completed', models.PositiveIntegerField(default=0)),
                ('maintenance_completed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_auxiliar_sistemas',
            },
        ),
    ]
