# Generated by Django 3.0.11 on 2021-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('name', models.CharField(help_text='Nombre del implemento', max_length=70)),
                ('category', models.CharField(help_text='Categoria a la pertenece el implemento', max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('price', models.CharField(max_length=50)),
                ('status_implement', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tbl_inventario',
            },
        ),
        migrations.CreateModel(
            name='TechnicalDataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro', verbose_name='creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la ultima modificación', verbose_name='modificado el')),
                ('picture', models.ImageField(blank=True, default='inventory/pictures/default-image.png', null=True, upload_to='inventory/pictures')),
                ('brand_implement', models.CharField(max_length=50)),
                ('model_implement', models.CharField(max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('specifications', models.TextField(help_text='Especificaciones tecnicas del implemento')),
            ],
            options={
                'db_table': 'tbl_ficha_tecnica',
            },
        ),
    ]
